version: '3'

services:
  mongo:
    image: mongo
    restart: always
    ports:
    - "27018:27017"
  api_server:
    build:
      dockerfile: Dockerfile.dev
      context: .
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./:/app